### PR TITLE
MDL-57316 media: Add mov to test video media players

### PR DESCRIPTION
**Pull request by xow**

### CODE REVIEW

**Comment by danpoltawski** [comment]
Can you explain a bit about this? It looks like a zero byte file?

**Comment by danpoltawski** [comment]
We do already have a special directory on download.moodle.org with the following:
http://download.moodle.org/mediatest/
audiotest.aac  audiotest.mp3  audiotest.ra   divx_320_180.avi        flashvideohd_720_400.f4v  mpeg_320_180.avi   quicktime_320_180.mov   theora_320_180.ogv  wmv_320_180.wmv
audiotest.m4a  audiotest.ogg  audiotest.wav  flashvideo_320_180.flv  index.html                mpeg4_320_180.m4v  realvideo_320_180.rmvb  webm_320_180.webm

**Comment by xow** [comment]
Ah, didn't know thanks Dan!

**Comment by danpoltawski** [comment]
(I doubt its documented anywhere, so I wouldn't expect you to :))

**Pull request closed without merging**
