### PR TITLE
MDLSITE-5297 redir: Correct server var for hostname

### PR DESCRIPTION
**Pull request by andrewnicols**

### CODE REVIEW

**Comment by andrewnicols** [comment]
Essentially we currently use HTTP_HOST, and we should use SERVER_NAME.

```
  ["HTTP_HOST"]=>
  string(14) "localhost:8080"
  ["SERVER_NAME"]=>
  string(9) "localhost"
```

Since we already concatenate the port onto the URL in those tests, we currently end up trying to redirect to:
```
localhost:8080:8080
```

**Comment by stronk7** [comment]
Is it MDLSITE-5926 correct? Cannot find it.

**Comment by andrewnicols** [comment]
Ahem - thanks Eloy, It was MDLSITE-5296. Force pushing now.

**Comment by andrewnicols** [comment]
Still wrong /o\ https://tracker.moodle.org/browse/MDLSITE-5297

**Comment by andrewnicols** [comment]
Moved to #13 with the correct branch + issue #.

**Comment by stronk7** [comment]
was fun to read the iterations of this via email, lol. Looking to #13... now.

**Pull request closed without merging**
